# Create dev env for Debian based systems
# Remember logout and login back in to make installations work

- name: Create development environment
  hosts: localhost 
  become: yes
  tasks:

    - name: Ensure Git is installed
      ansible.builtin.package:
        name: git
        state: present

    - name: Ensure cURL is installed
      ansible.builtin.package:
        name: curl
        state: present

    - name: Ensure python3 is installed
      ansible.builtin.package:
        name: python3
        state: present

    - name: Install apt packages
      become_method: sudo
      ansible.builtin.apt:
        pkg:
          - neovim
          - jq
          - python3-pip
          - btop

    - name: Run Roles
      include_role:
          name: "{{ item }}"
      loop:
        - go
        - rust  
        - docker
        - vscodium
        - zsh