# Create dev env for Debian based systems
# Remember logout and login back in to make installations update

- name: Create development environment
  hosts: localhost
  tasks:
    - name: Install apt packages
      become: yes
      become_method: sudo
      ansible.builtin.apt:
        pkg:
          - neovim
          - jq
          - python3-pip
          - btop
          - fzf
          - mpv

    - name: Run Roles
      include_role:
        name: "{{ item }}"
      loop:
        - go
        - rust
        - docker
        - zsh
