- name: Install/Check for Flatpak
  package:
    name: flatpak
    state: present

- name: Add Flathub repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  args:
    creates: /var/lib/flatpak/repo/flathub

- name: Install VSCodium from Flathub
  command: flatpak install -y --system flathub com.vscodium.codium