- name: Add GPG VSCodium key of the repository
  ansible.builtin.shell: "wget -qO - https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg | gpg --dearmor | sudo dd of=/usr/share/keyrings/vscodium-archive-keyring.gpg"

- name: Add VSCodium repository
  ansible.builtin.shell: "echo 'deb [ signed-by=/usr/share/keyrings/vscodium-archive-keyring.gpg ] https://download.vscodium.com/debs vscodium main' | sudo tee /etc/apt/sources.list.d/vscodium.list"

- name: Update repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install VSCodium
  ansible.builtin.apt:
    name: codium
    state: present
  become: true