- name: Check if Docker is installed
  ansible.builtin.stat:
    path: /usr/bin/docker
  register: docker_stat

- name: Download Docker installation script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'
  when: not docker_stat.stat.exists

- name: Run Docker installation script
  ansible.builtin.command: /tmp/get-docker.sh
  become_user: "{{ ansible_env.USER }}"
  when: not docker_stat.stat.exists

- name: Remove Docker installation script
  ansible.builtin.file:
    path: /tmp/get-docker.sh
    state: absent
  when: not docker_stat.stat.exists